### ISSUE TITLE
Runtime error in Dart2: '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, List<String>>'

### ISSUE THREAD

**Issue by ameiyil** [dart-lang/googleapis#37]
After migrating to Dart2, there are "invalid cast" errors being thrown when using the Dart Google API clients to call the server.

It stems from trying to implicitly downcast a generic `Map` to a `Map<String, List<String>>` on line 66 in clients.dart:
```
type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, List<String>>' where
  _InternalLinkedHashMap is from dart:collection
  Map is from dart:core
  String is from dart:core
  List is from dart:core
  String is from dart:core

#0      ApiRequester.request (package:_discoveryapis_commons/src/clients.dart:66)
#1      PeopleConnectionsResourceApi.list (package:googleapis/people/v1.dart:982)
```

**Comment by mkustermann** [comment]
@jakobr-google Weren't you looking into this issue recently?

**Comment by jakobr-google** [comment]
I'll track all the Dart 2 issues in #35.
