### ISSUE TITLE
CalendarApi: EventExtendedProperties.fromJson still not Dart2 clean

### ISSUE THREAD

**Issue by pulyaevskiy** [dart-lang/googleapis#39]
With 0.50.1:

```
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>' where
  _InternalLinkedHashMap is from dart:collection
  String is from dart:core
  Map is from dart:core
  String is from dart:core
  String is from dart:core

#0      new EventExtendedProperties.fromJson (package:googleapis/calendar/v3.dart:4162:22)
#1      new Event.fromJson (package:googleapis/calendar/v3.dart:4635:15)
#2      new Events.fromJson.<anonymous closure> (package:googleapis/calendar/v3.dart:5163:38)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      new Events.fromJson (package:googleapis/calendar/v3.dart:5164:12)
#6      EventsResourceApi.list.<anonymous closure> (package:googleapis/calendar/v3.dart:1996:41)
#7      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#9      <…>
```

**Comment by mkustermann** [comment]
@jakobr-google was looking into this iirc.

**Comment by jakobr-google** [comment]
Yep. Unfortunately, we only get these errors at runtime, so we pretty much have to catch and fix them one by one.

I'll look into this one.

**Comment by jakobr-google** [comment]
I'll track all the Dart 2 issues in #35.
