### ISSUE TITLE
Firestore RestAPI runQuery

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/googleapis#83]
I'm trying to use runQuery via the rest API:
https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases.documents/runQuery

This is my code:

```dart
  final search = await fs.projects.databases.documents.runQuery(
      RunQueryRequest.fromJson({
        'structuredQuery': {
          'where': {
            'fieldFilter': {
              'field': {'fieldPath': 'dnUuid'}
            },
            'op': 'EQUAL',
            'value': {'integerValue': account.dnUid}
          }
        }
      }),
      'projects/osapp/databases/(default)/documents/account');
```

I'm getting the following error:
```
Unhandled exception:
DetailedApiRequestError(status: 400, message: Invalid JSON payload received. Unknown name "structuredQuery" at 'document': Cannot find field.)
#0      _validateResponse (package:_discoveryapis_commons/src/clients.dart:852:9)
<asynchronous suspension>
#1      ApiRequester.request (package:_discoveryapis_commons/src/clients.dart:74:22)
<asynchronous suspension>
#2      ProjectsDatabasesDocumentsResourceApi.runQuery (package:googleapis/firestore/v1.dart:1438:32)
#3      migrateAccount (package:migration/migration.dart:181:56)
<asynchronous suspension>
#4      startMigration (package:migration/migration.dart:73:15)
<asynchronous suspension>
#5      main (file:///Users/jimmyff/Development/onescene/migration/bin/server.dart:7:9)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
The terminal process terminated with exit code: 255
```

The error isn't very helpful and I can't find any example or documentation about how to query via the Rest API. 

I don't suppose you know what I'm doing wrong?

**Comment by jimmyff** [comment]
For anyone interested here was the solution:

```
  final search = await fs.projects.databases.documents.runQuery(
      RunQueryRequest()
        ..structuredQuery = (StructuredQuery()
          ..from = [CollectionSelector()..collectionId = 'account']
          ..where = (Filter()
            ..fieldFilter = (FieldFilter()
              ..field = (FieldReference()..fieldPath = 'dnUuid')
              ..op = 'EQUAL'
              ..value = (Value()..integerValue = account.dnUid)))),
      'projects/osapp/databases/(default)/documents');
```

**Comment by joysitar** [comment]
Hi could you access the API using runQuery in API explorer?
