### ISSUE TITLE
Type exception from fs.projects.databases.documents.runQuery

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/googleapis#88]
Hey @jonasfj (I think you're the only person that responds to tickets on this repo), don't suppose you could have a look at this issue I'm having?

I get the following error: 
```
List<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>'
```
When I run the a firestore query via the rest API:

```dart
  final search = await fs.projects.databases.documents.runQuery(
      RunQueryRequest()
        ..structuredQuery = (StructuredQuery()
          ..from = [CollectionSelector()..collectionId = 'account']
          ..where = (Filter()
            ..fieldFilter = (FieldFilter()
              ..field = (FieldReference()..fieldPath = 'dnUuid')
              ..op = 'EQUAL'
              ..value = (Value()..integerValue = account.dnUuid)))),
      'projects/osapp/databases/(default)/documents');
```

### Full exception

```
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'Map<dynamic, dynamic>'
#0      ProjectsDatabasesDocumentsResourceApi.runQuery.<anonymous closure> (package:googleapis/firestore/v1.dart:1444:67)
#1      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#6      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#7      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#8      ApiRequester.request (package:_discoveryapis_commons/src/clients.dart)
<asynchronous suspension>
#9      ProjectsDatabasesDocumentsResourceApi.runQuery (package:googleapis/firestore/v1.dart:1438:32)
#10     migrateAccount (package:migration/migration.dart:195:56)
<asynchronous suspension>
#11     startMigration (package:migration/migration.dart:73:15)
<asynchronous suspension>
#12     main (file:///Users/jimmyff/Development/onescene/migration/bin/server.dart:7:9)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

It looks like the problem is that `RunQueryResponse.fromJson` is expecting data of type `Map<dynamic, dynamic>` however the response from `_requester.request()` is returning a `List` rather than `Map`

### package versions:

  googleapis 0.54.0
  googleapis_auth 0.2.11+1

**Comment by JSANL** [comment]
Propably #25. 
Youll need to run the Query manually with the authenticated http client.

**Comment by kevmoo** [comment]
We've regenerated the APIs with much higher fidelity. Please try again and comment here if you're still having the issue!

**Comment by jonasfj** [comment]
Last I looked into this there was a problem with discovery API documents, which isn't something we can fix in this project.

**Comment by Jonas-Sander** [comment]
https://pub.dev/documentation/googleapis/latest/firestore.v1/RunQueryResponse-class.html

There is still only a single `document`.

**Comment by Jonas-Sander** [comment]
Then let's leave it open at least so other people can directly see it's not fixed?
